version: "3.8"

services:
  api:
    build: 
      context: .
      dockerfile: ./api/Dockerfile
    container_name: ${APP_API_NAME}
    ports:
      - ${APP_API_PORT}:${APP_API_PORT}
    volumes:
      - ./api:/opt/app/api
      - gem_cache:/usr/local/bundle/gems
    depends_on:
      - api-db
    env_file: .env
    environment:
      RAILS_ENV: ${RAILS_ENV}
    networks:
      - app_network

  api-db:
    image: postgres
    container_name: ${DATABASE_HOST}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./api/log/db:/logs
    env_file: .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - app_network

  client:
    build: 
      context: .
      dockerfile: ./client/Dockerfile
    container_name: ${APP_CLIENT_NAME}
    ports:
      - ${APP_CLIENT_PORT}:${APP_CLIENT_PORT}
    volumes:
      - ./client:/opt/app/client
      - node_modules:/opt/app/client/node_modules  
    env_file: .env
    environment:
      NODE_ENV: ${NODE_ENV}

networks:
  app_network:

volumes:
  gem_cache:
  db_data:
  node_modules:  