name: ci/cd deploy

on:
  push: # any branch
  pull_request:
    branches:
      - master

jobs:      
  build:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: docker-compose up --build -d

      - name: test_api
        run: docker-compose run -e "RAILS_ENV=test" --rm api
      
      - name: test_client
        run: docker-compose run -e "NODE_ENV=test" --rm client

      
  