name: Push api to Heroku

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Release API
      uses: akhileshns/heroku-deploy@v3.0.4
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "backend-gces"
        heroku_email: "guilyra12@gmail.com"
      env:
        HD_APP_BASE: "api"
