name: ci/cd deploy

# tho i could push those containers built at the integration job
# and then use them as containers images for the coverage job
# i prefer not to, since docker is currently limiting pulls and pushes, so idk

on:
  push: # any branch
  pull_request:
    branches:
      - master

jobs:
  integration:
    name: CI  &&  Test inside docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: directory          
        run: ls -a          

      - name: build
        run: docker-compose up --build -d

      - name: test_api
        run: docker-compose run -e "RAILS_ENV=test" api
      
      - name: test_client
        run: docker-compose run -e "NODE_ENV=test" client

